# Generated by Django 4.2.1 on 2023-07-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalidation',
            name='id_password',
        ),
        migrations.AddField(
            model_name='emailvalidation',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PasswordValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation', models.BooleanField()),
                ('id_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata')),
            ],
        ),
    ]
