# Generated by Django 4.2.1 on 2023-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_emailvalidation_id_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidation',
            name='otp',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
