# Generated by Django 4.2.1 on 2023-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userdata_email_alter_userdata_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='emailvalidation',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
